# These are supported funding model platforms

github: [Unix-like-SoN] # Replace with your GitHub username
telegram: [@UnixFibers] # Replace with your Patreon username
custom: ["USDT(TRC-20): TDnjDg9HxySo1J2FPSrvWQejyZ4gHKiXSJ", "USDT(BEP-20): 0x4f85f29892b261fa8029f3cfd64211e166744733"] # Example for custom links or crypto wallet
